config/routes.rb
Foodfight::Application.routes.draw do
  resources :fights, :only => [:show, :create] do
    member do
      put 'vote_for_1'
      put 'vote_for_2'
    end
  end
  
  resources :searches, :only => [:new, :show, :create]

  match ':token' => 'session#create'

  root :to => 'searches#new'

end

app/models/fight.rb
class Fight < ActiveRecord::Base
  belongs_to :restaurant_1, :class_name => Restaurant
  belongs_to :restaurant_2, :class_name => Restaurant
  has_many :users
  
  def vote_for_1
    self.votes_for_1 ||= 0
    self.votes_for_1 += 1
    save
  end
  
  def vote_for_2
    self.votes_for_2 ||= 0
    self.votes_for_2 += 1
    save
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  def self.create_or_update(yelp_id, response)
    restaurant = Restaurant.find_by_yelp_id(yelp_id)
    
    if restaurant
      restaurant.update_attributes({:response => response})
    else
      Restaurant.create({:yelp_id => response['id'], :response => response})
    end
  end
  
  
  def response=(object)
    @response = object
    write_attribute(:response, object.to_json)
  end
  
  def response
    @response ||= JSON.parse(read_attribute(:response)) unless read_attribute(:response).blank?
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  def response=(object)
    @response = object
    write_attribute(:response, object.to_json)
  end
  
  def response
    @response ||= JSON.parse(read_attribute(:response)) unless read_attribute(:response).blank?
  end
  
  def search
    return true if response && (Time.now - self.updated_at < 1.day)
    
    # move this into some sort of async queue
    @client ||= Yelp::Client.new
    
    search_params = {
      :city => 'Vancouver',
      :state => 'BC',
      :yws_id => YELP_YWSID
    }
    
    search_params[:term] = self.query unless self.query.blank?
    search_params[:category] = self.category unless self.category.blank?
    
    request = Yelp::Review::Request::Location.new(search_params)
    temp_response = @client.search(request)
    
    puts temp_response.inspect
    
    if temp_response['message']['text'] == 'OK'
      self.response = temp_response['businesses']
      create_restaurants
      save
    else
      false
    end
  end
  
  private
  
  def create_restaurants
    if response && response.length > 0
      response.each do |r|
        Restaurant.create_or_update(r['id'],r)
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :generate_token
  
  belongs_to :fight
  
  private
  
  def generate_token
    self.token = SecureRandom.uuid
  end
end

app/models/war.rb
class War < ActiveRecord::Base
  belongs_to :restaurant_1, :class_name => Restaurant
  belongs_to :restaurant_2, :class_name => Restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  # GET /fights
  # GET /fights.json
  # def index
  #   @fights = Fight.all
  # 
  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @fights }
  #   end
  # end

  # GET /fights/1
  # GET /fights/1.json
  def show
    @fight = Fight.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fight }
    end
  end

  # GET /fights/new
  # GET /fights/new.json
  # def new
  #   @fight = Fight.new
  # 
  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @fight }
  #   end
  # end

  # GET /fights/1/edit
  # def edit
  #   @fight = Fight.find(params[:id])
  # end

  # POST /fights
  # POST /fights.json
  def create
    @fight = Fight.new(params[:fight])

    respond_to do |format|
      if @fight.save
        format.html { redirect_to @fight, notice: 'Fight was successfully created.' }
        format.json { render json: @fight, status: :created, location: @fight }
      else
        format.html { render action: "new" }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def vote_for_1
    @fight = Fight.find(params[:id])
    
    respond_to do |format|
      if @fight.vote_for_1
        format.html { redirect_to @fight, notice: 'Voted for 1 successfully.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def vote_for_2
    @fight = Fight.find(params[:id])
    
    respond_to do |format|
      if @fight.vote_for_2
        format.html { redirect_to @fight, notice: 'Voted for 1 successfully.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fights/1
  # PUT /fights/1.json
  # def update
  #   @fight = Fight.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @fight.update_attributes(params[:fight])
  #       format.html { redirect_to @fight, notice: 'Fight was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @fight.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /fights/1
  # DELETE /fights/1.json
  # def destroy
  #   @fight = Fight.find(params[:id])
  #   @fight.destroy
  # 
  #   respond_to do |format|
  #     format.html { redirect_to fights_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.json
  #   def index
  #     respond_to do |format|
  #       format.html # index.html.erb
  #       format.json { render json: @searches }
  #     end
  #   end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new
    @location = request.location.city
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # POST /searches
  # POST /searches.json
  def create
    params[:search][:query].strip!
    params[:search][:category].strip!
    
    @search = Search.find_or_create_by_query_and_category(params[:search][:query], params[:search][:category])
    
    respond_to do |format|
      if @search.search
        # format.html { redirect_to @search, notice: 'Search was successfully created.' }
        # format.json { render json: @search, status: :created, location: @search }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  
  def find_location
    @client_ip = request.remote_ip
    location = IpGeocoder.geocode(@client_ip)
    return location  
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    @user = User.find_by_token(params[:token])
    
    if @user
      session[:user_id] = @user.id
      redirect_to @user.fight
    else
      
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/fights/_form.html.erb
<%= form_for(@fight) do |f| %>
  <% if @fight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fight.errors.count, "error") %> prohibited this fight from being saved:</h2>

      <ul>
      <% @fight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :restaurant_1_id %><br />
    <%= f.number_field :restaurant_1_id %>
  </div>
  <div class="field">
    <%= f.label :restaurant_2_id %><br />
    <%= f.number_field :restaurant_2_id %>
  </div>
  <div class="field">
    <%= f.label :votes_for_1 %><br />
    <%= f.number_field :votes_for_1 %>
  </div>
  <div class="field">
    <%= f.label :votes_for_2 %><br />
    <%= f.number_field :votes_for_2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fights/_result.html.erb
<div class="restaurant_x">
  <span class="restaurant_photo"><%= image_tag result['photo_url'] %></span>
  <span class="restaurant_name"><%= result['name'] %></span>
  <span class="restaurant_rating"><%= image_tag result['rating_img_url'] %></span>
  <span class="restaurant_rating"><%= image_tag result['rating_img_url'] %></span>
  <span class="restaurant_address"><%= result['address1'] %></span>
  <span class="restaurant_phone_number"><%= result['phone'] %></span>
</div>

app/views/fights/show.html.erb
<div style="text-align: center"><div id="fight">

<%= render :partial => "result", :locals => { :result => @fight.restaurant_1.response } %>


<div>
  <b>Votes:</b>
  <%= @fight.votes_for_1 %> [<%= link_to '+', vote_for_1_fight_path(@fight), method: :put %>]
</div>

<%= render :partial => "result", :locals => { :result => @fight.restaurant_2.response } %>


<div>
  <b>Votes:</b>
  <%= @fight.votes_for_2 %> [<%= link_to '+', vote_for_2_fight_path(@fight), method: :put %>]
</div>

</div></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Food Fight! Two restaurants enter, only one restaurant leaves! What you want to have for lunch?</title>

	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

	<!-- GOOGLE FONTS -->
	<link href='http://fonts.googleapis.com/css?family=Patrick+Hand|Permanent+Marker|Walter+Turncoat' rel='stylesheet' type='text/css'>
	
	<!--<meta name="viewport" content="width=device-width, target-densitydpi=160dpi, initial-scale=1.0">-->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="apple-mobile-web-app-capable" content="yes">
</head>
<body>

<div class="container">

	<div id="header">
		<a href="/" class="logo"><img src="../../assets/logo.png" alt="Food Fight!" /></a>
	</div>
	<%= yield %>
	<div id="footer">
		<ul>
			<li><a href="">About this App</a></li>
			<li>&copy; 2012 Derp.</li>
		</ul>
	</div>
</div>

</body>
</html>

app/views/searches/_form.html.erb
<%= form_for(@search, :remote => true) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field search">
    <%= f.text_field :query %>
  </div>
  <div class="field category">
    <%= f.label :category %><br />
    <%= f.select :category, YELP_RESTAURANT_CATEGORIES, :include_blank => true %>
  </div>
  <div class="actions">
    <%= f.submit 'Search!' %>
  </div>
<% end %>

app/views/searches/_results.html.erb
<% results.each do |result| %>
<li>
  <span class="restaurant_name"><%= result['name'] %></span>
  <span class="restaurant_rating"><%= image_tag result['rating_img_url'] %></span>
  <span class="restaurant_address"><%= result['address1'] %></span>
  <span class="restaurant_phone_number"><%= result['phone'] %></span>
</li>
<% end %>

app/views/searches/create.js.erb
$('#results').html("<%= escape_javascript(render :partial => "results", :locals => { :results => @search.response}) %>");

app/views/searches/new.html.erb
<div id="content" class="home vancouver">

	<div id="intro" class="grid_3">
		<p class="narrate top left">
			In the city of <strong>Vancouver</strong>...
		</p>
		<div class="col panel panel1">
		</div>
		<div class="col panel panel2 nomobile">
		</div>
		<div class="col panel panel3 nomobile">
		</div>
		<p class="narrate bottom right emphasis">
			A group of friends can't decide where to eat...
		</p>
	</div>

	<div id="step1" class="process step search">
		<h3 class="narrate top left dark">Select your first challenger:</h3>

		<%= render 'form' %>
		
		<ul id="results">
		</ul>
	</div>
</div>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Query:</b>
  <%= @search.query %>
</p>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>

app/views/wars/_form.html.erb
<%= form_for(@war) do |f| %>
  <% if @war.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@war.errors.count, "error") %> prohibited this war from being saved:</h2>

      <ul>
      <% @war.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :restaurant_1_id %><br />
    <%= f.number_field :restaurant_1_id %>
  </div>
  <div class="field">
    <%= f.label :restaurant_2_id %><br />
    <%= f.number_field :restaurant_2_id %>
  </div>
  <div class="field">
    <%= f.label :votes_for_1 %><br />
    <%= f.number_field :votes_for_1 %>
  </div>
  <div class="field">
    <%= f.label :votes_for_2 %><br />
    <%= f.number_field :votes_for_2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Restaurant 1:</b>
  <%= @war.restaurant_1_id %>
</p>

<p>
  <b>Restaurant 2:</b>
  <%= @war.restaurant_2_id %>
</p>

<p>
  <b>Votes for 1:</b>
  <%= @war.votes_for_1 %>
</p>

<p>
  <b>Votes for 2:</b>
  <%= @war.votes_for_2 %>
</p>